/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hust.group11.ecobikerentalgroup11.boundary.admin;

/**
 *
 * @author Hoang Duc
 */
import com.hust.group11.ecobikerentalgroup11.Constants;
import com.hust.group11.ecobikerentalgroup11.DataBase;
import com.hust.group11.ecobikerentalgroup11.Entity.Bike;
import com.hust.group11.ecobikerentalgroup11.Entity.DockingPoint;
import com.hust.group11.ecobikerentalgroup11.Entity.Station;
import com.hust.group11.ecobikerentalgroup11.Entity.User;

import javax.swing.RowFilter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import com.hust.group11.ecobikerentalgroup11.MainEntry;
import java.io.File;
import java.sql.PreparedStatement;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileSystemView;
import jdk.nashorn.internal.objects.NativeArray;

public class AdminAddBike extends javax.swing.JFrame {

    /**
     * Creates new form FindStationScreen
     */
    
    File fileBarCode;
    private JFrame backScreen;
    private ArrayList<Station> arrStation;
    private DataBase db;
    private User user;
    private Station passStation;

    public AdminAddBike(User user, JFrame backScreen) throws SQLException {
        initComponents();
        this.backScreen = backScreen;
        this.db = new DataBase();
        this.user = user;
        addStation();
    }

    public void addStation() {
        arrStation = new ArrayList<>();
        try {
            String sqlString = "select * from station";
            ResultSet rs = db.query(sqlString);
            while (rs.next()) {
                Station station = new Station(0, 0, 0, 0, "", "", "");
                station.setAddress(rs.getString("address"));
                station.setStationId(rs.getInt("station_id"));
                station.setStationName(rs.getString("station_name"));
                station.setStationArea(rs.getInt("area"));
                station.setLocationCode(rs.getString("location_code"));
                arrStation.add(station);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }

        for (Station x : arrStation) {
            cbbStation.addItem(x.getStationName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jFileChooser1 = new javax.swing.JFileChooser();
        btnCancel = new javax.swing.JButton();
        btnAddBike = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfModel = new javax.swing.JTextField();
        tfPlateLiscense = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfDockingPoint = new javax.swing.JTextField();
        tfBattery = new javax.swing.JTextField();
        cbbStation = new javax.swing.JComboBox<>();
        tfBrand = new javax.swing.JTextField();
        tfPrice = new javax.swing.JTextField();
        cbbBikeType = new javax.swing.JComboBox<>();
        dcOperationDate = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        btnAddBikeImage = new javax.swing.JButton();
        imageCodePanel = new com.hust.group11.ecobikerentalgroup11.boundary.ImageCodePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Bike");
        setResizable(false);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnAddBike.setText("Add");
        btnAddBike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBikeActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ADD BIKE");

        jLabel6.setText("Station :");

        jLabel7.setText("Plate Liscense :");

        jLabel8.setText("Brand :");

        jLabel9.setText("Model :");

        jLabel10.setText("Battery :");

        jLabel11.setText("Operation Date :");

        jLabel12.setText("Bike Type :");

        jLabel13.setText("Price :");

        jLabel1.setText("Docking point :");

        cbbBikeType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single Bike", "Double Bike", "Electrical Bike" }));

        dcOperationDate.setDateFormatString("dd/MM/yyyy");

        jLabel2.setText("Image :");

        btnAddBikeImage.setText("Add Image");
        btnAddBikeImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBikeImageActionPerformed(evt);
            }
        });

        imageCodePanel.setPreferredSize(new java.awt.Dimension(178, 178));

        javax.swing.GroupLayout imageCodePanelLayout = new javax.swing.GroupLayout(imageCodePanel);
        imageCodePanel.setLayout(imageCodePanelLayout);
        imageCodePanelLayout.setHorizontalGroup(
            imageCodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );
        imageCodePanelLayout.setVerticalGroup(
            imageCodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfDockingPoint, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(cbbBikeType, 0, 1, Short.MAX_VALUE)
                            .addComponent(tfBattery))))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(54, 54, 54)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfModel)
                                .addComponent(tfPlateLiscense, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbbStation, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfBrand, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(178, 178, 178))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddBikeImage)
                            .addComponent(dcOperationDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imageCodePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCancel)
                                .addGap(31, 31, 31)
                                .addComponent(btnAddBike, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(69, 69, 69)))
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbbStation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(tfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfPlateLiscense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(cbbBikeType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(tfBattery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(tfDockingPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dcOperationDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddBikeImage)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(imageCodePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddBike)
                    .addComponent(btnCancel))
                .addGap(19, 19, 19))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        MainEntry.move(this, backScreen);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAddBikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBikeActionPerformed
        DateFormat fm = new SimpleDateFormat("dd/MM/yyyy");
        String station = cbbStation.getSelectedItem().toString(),
                plateLiscense = tfPlateLiscense.getText(),
                model = tfModel.getText(),
                brand = tfBrand.getText(),
                price = tfPrice.getText(),
                bikeType = cbbBikeType.getSelectedItem().toString(),
                battery = tfBattery.getText(),
                dockingPoint = tfDockingPoint.getText(),
                OPdate = fm.format(dcOperationDate.getDate());
        //add dockinglock
        String sql = "INSERT INTO `docking_lock` (`lock_id`, `station_id`, `bar_code`, `status`) VALUES\n"
                + "(null, " + getStationIDByName(station) + ", '" + plateLiscense + "', 1)";
        int lockID = -1;
        try {
            ResultSet rs = db.insert(sql);
            rs.next();
            lockID = rs.getInt(1);
        } catch (SQLException ex) {
            Logger.getLogger(AdminAddBike.class.getName()).log(Level.SEVERE, null, ex);
        }

        //add Bike
        sql = "INSERT INTO `bike` (`bike_id`, `station_id`, `lock_id`, `plate_license`, `brand`, `model`, `battery`, `operation_date`, `type`, `status`, `value_of_bike`, `image`) VALUES\n"
                + "(null, " + getStationIDByName(station)
                + ", " + lockID
                + ", '" + plateLiscense
                + "', '" + brand
                + "', '" + model
                + "', " + battery
                + ", '" + OPdate
                + "', '" + bikeType
                + "', 0, " + price
                + ", 'bike_default.png')";
    }//GEN-LAST:event_btnAddBikeActionPerformed

    private void btnAddBikeImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBikeImageActionPerformed
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView());
        File wd = new File(System.getProperty("user.dir"));
        jfc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        jfc.setCurrentDirectory(wd);
        int r = jfc.showSaveDialog(null);
        if (r == JFileChooser.APPROVE_OPTION) {
            //addFileLabel.setText(jfc.getSelectedFile().getName());
            fileBarCode = jfc.getSelectedFile();
            imageCodePanel.showImage(jfc.getSelectedFile());
            imageCodePanel.repaint();
        } else {
            //addFileLabel.setText("You choose no file");
        }
    }//GEN-LAST:event_btnAddBikeImageActionPerformed

    private int getStationIDByName(String stationName) {
        int ID = -1;
        for (Station x : arrStation) {
            if (x.getStationName().equals(stationName)) {
                ID = x.getStationId();
                break;
            }
        }
        return ID;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBike;
    private javax.swing.JButton btnAddBikeImage;
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox<String> cbbBikeType;
    private javax.swing.JComboBox<String> cbbStation;
    private com.toedter.calendar.JDateChooser dcOperationDate;
    private com.hust.group11.ecobikerentalgroup11.boundary.ImageCodePanel imageCodePanel;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tfBattery;
    private javax.swing.JTextField tfBrand;
    private javax.swing.JTextField tfDockingPoint;
    private javax.swing.JTextField tfModel;
    private javax.swing.JTextField tfPlateLiscense;
    private javax.swing.JTextField tfPrice;
    // End of variables declaration//GEN-END:variables
}
