/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hust.group11.ecobikerentalgroup11.boundary;

import com.hust.group11.ecobikerentalgroup11.DataBase;
import com.hust.group11.ecobikerentalgroup11.MainEntry;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Nguyen Thanh Long
 */
public class AddPayentMethodScreen extends javax.swing.JFrame {

    /**
     * Creates new form AddPayentMethodScreen
     */
    private DataBase db;
    JFrame backScreen;
    public AddPayentMethodScreen(JFrame backScreen) throws SQLException {
        initComponents();
        db = new DataBase();
        this.backScreen = backScreen;
    }

    private AddPayentMethodScreen() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namePaymentMethodFiled = new javax.swing.JTextField();
        namePaymentMethodLabel = new javax.swing.JLabel();
        cardCodeLabel = new javax.swing.JLabel();
        cardCodeField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nameOwnerLabel = new javax.swing.JLabel();
        nameOwnerField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cvvCodeLabel = new javax.swing.JLabel();
        cvvCodeField = new javax.swing.JTextField();
        dateExpiredLabel = new javax.swing.JLabel();
        dateExpiredField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Payment Method");
        setResizable(false);

        namePaymentMethodFiled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namePaymentMethodFiledActionPerformed(evt);
            }
        });

        namePaymentMethodLabel.setText("Name Payment Method");

        cardCodeLabel.setText("Card Code");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("FILL INFORMATION PAYMENT ACCOUNT");

        nameOwnerLabel.setText("Name Owner");

        nameOwnerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameOwnerFieldActionPerformed(evt);
            }
        });

        jButton1.setText("Add Method");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMethodActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        cvvCodeLabel.setText("Cvv Code");

        dateExpiredLabel.setText("Date Expired");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jButton2)
                        .addGap(31, 31, 31)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namePaymentMethodLabel)
                            .addComponent(nameOwnerLabel)
                            .addComponent(cardCodeLabel)
                            .addComponent(cvvCodeLabel)
                            .addComponent(dateExpiredLabel))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cardCodeField)
                            .addComponent(nameOwnerField)
                            .addComponent(namePaymentMethodFiled)
                            .addComponent(cvvCodeField)
                            .addComponent(dateExpiredField, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namePaymentMethodFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namePaymentMethodLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardCodeLabel)
                    .addComponent(cardCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameOwnerLabel)
                    .addComponent(nameOwnerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cvvCodeLabel)
                    .addComponent(cvvCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateExpiredLabel)
                    .addComponent(dateExpiredField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void namePaymentMethodFiledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namePaymentMethodFiledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namePaymentMethodFiledActionPerformed

    private void nameOwnerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameOwnerFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameOwnerFieldActionPerformed

    private void addMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMethodActionPerformed
        System.out.println("add method here");
        String nameMethod = namePaymentMethodFiled.getText();
        String cardCode = cardCodeField.getText();
        String nameOwner = nameOwnerField.getText();
        String cvvCode = cvvCodeField.getText();
        String dateExpired = dateExpiredField.getText();
        try {
            String sqlString = "Insert into payment_method values (null, '"+ nameMethod +"', '" +cardCode+ "', '"+nameOwner+"', '"+cvvCode+"', '" +dateExpired+ "')";
            System.out.println(sqlString);
            ResultSet rs = db.insert(sqlString);
            rs.next();
            int pk = rs.getInt(1);
            System.out.println("pk: " + pk);
            if(pk > 0){
                MainEntry.move(this, backScreen);
                JOptionPane.showMessageDialog(backScreen, "Create success");
            } else {
                JOptionPane.showMessageDialog(this, "Create fail");
            }
        } catch (SQLException sqlException) {
            sqlException.printStackTrace();
        }
    }//GEN-LAST:event_addMethodActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        MainEntry.move(this, backScreen);
    }//GEN-LAST:event_backActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cardCodeField;
    private javax.swing.JLabel cardCodeLabel;
    private javax.swing.JTextField cvvCodeField;
    private javax.swing.JLabel cvvCodeLabel;
    private javax.swing.JTextField dateExpiredField;
    private javax.swing.JLabel dateExpiredLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nameOwnerField;
    private javax.swing.JLabel nameOwnerLabel;
    private javax.swing.JTextField namePaymentMethodFiled;
    private javax.swing.JLabel namePaymentMethodLabel;
    // End of variables declaration//GEN-END:variables
}
