/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hust.group11.ecobikerentalgroup11.boundary;

import com.hust.group11.ecobikerentalgroup11.Constants;
import com.hust.group11.ecobikerentalgroup11.Entity.Bike;
import com.hust.group11.ecobikerentalgroup11.Entity.Transaction;
import com.hust.group11.ecobikerentalgroup11.Entity.User;
import com.hust.group11.ecobikerentalgroup11.MainEntry;
import java.io.File;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nguyencongluat
 */
public class RentingScreen extends javax.swing.JFrame {

    /**
     * Creates new form Renting
     */
    private JFrame backScreen;
    private Bike bike;
    private User user;
    private Transaction transaction;

    public RentingScreen(Transaction transaction, User user, Bike bike, JFrame backScreen) {
        initComponents();
        this.backScreen = backScreen;
        this.bike = bike;
        this.user = user;
        this.transaction = transaction;
        try {
            showInfoTable(transaction, bike);
        } catch (ParseException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }

    public void showInfoTable(Transaction transaction, Bike bike) throws ParseException {

        DefaultTableModel model = (DefaultTableModel) rentingBikeTable.getModel();
        System.out.println("set Model here");
        model.setValueAt(bike.getLicensePlate(), 0, 1);
        model.setValueAt(bike.getType(), 1, 1);
        model.setValueAt(bike.getBattery(), 2, 1);
        model.setValueAt(bike.getBrand(), 3, 1);
        model.setValueAt(bike.getModel(), 4, 1);
        model.setValueAt(bike.getStatus(), 5, 1);
        model.setValueAt(bike.getValue(), 6, 1);
        model.setValueAt(transaction.getStartTime(), 7, 1);

        String startTimeString = transaction.getStartTime();
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        Date startTime = formatter.parse(startTimeString);
        Timer t = new Timer();

        t.scheduleAtFixedRate(
                new TimerTask() {
            public void run() {
                long currentTime = System.currentTimeMillis();
                long rentingTime = currentTime - startTime.getTime();
//                	long day = TimeUnit.MILLISECONDS.toDays(rentingTime);
                long hour = rentingTime / (1000 * 60 * 60);
                long minutes = (rentingTime / (1000 * 60)) % 60;
                long seconds = (rentingTime / (1000)) % 60;
                String timeRentingString = Long.toString(hour) + ":" + Long.toString(minutes) + ":" + Long.toString(seconds);
                rentingTimeField.setText(timeRentingString);

                long timeMinu = rentingTime / (1000 * 60);
                long amountPayment = 0;
                if (timeMinu <= 10) {
                    amountPayment = 0;
                } else {
                    timeMinu -= 10;
                    if (timeMinu <= 30) {
                        amountPayment = (long) ((float) timeMinu / 30 * 10);
                    } else {
                        timeMinu -= 30;
                        amountPayment = 10 + timeMinu / 15 * 3;
                    }
                }
                String amountPaymentString = Long.toString(amountPayment);
                if (amountPayment != 0) {
                    amountPaymentString += "000 VND";
                } else {
                    amountPaymentString += " VND";
                }
                model.setValueAt(amountPaymentString, 8, 1);
            }
        },
                0, // run first occurrence immediatetly
                1000);
        System.out.println(System.getProperty("user.dir") + bike.getImage());
        imageCodePanel.showImage(new File(bike.getImage()));
        imageCodePanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        rentingBikeTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        imageCodePanel = new com.hust.group11.ecobikerentalgroup11.boundary.ImageCodePanel();
        rentingTimeLabel = new javax.swing.JLabel();
        rentingTimeField = new javax.swing.JTextField();
        backButton = new javax.swing.JToggleButton();
        returnButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Renting Information");
        setResizable(false);

        rentingBikeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"License Plates", null},
                {"Bike Type", null},
                {"Battery", null},
                {"Brand", null},
                {"Model", null},
                {"Status", null},
                {"Value Bike", null},
                {"Start Time", null},
                {"Current Payment", null}
            },
            new String [] {
                "Name", "Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(rentingBikeTable);
        if (rentingBikeTable.getColumnModel().getColumnCount() > 0) {
            rentingBikeTable.getColumnModel().getColumn(0).setResizable(false);
            rentingBikeTable.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Renting Information");

        javax.swing.GroupLayout imageCodePanelLayout = new javax.swing.GroupLayout(imageCodePanel);
        imageCodePanel.setLayout(imageCodePanelLayout);
        imageCodePanelLayout.setHorizontalGroup(
            imageCodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 147, Short.MAX_VALUE)
        );
        imageCodePanelLayout.setVerticalGroup(
            imageCodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 125, Short.MAX_VALUE)
        );

        rentingTimeLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rentingTimeLabel.setText("Renting Time:");

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        returnButton.setText("Return Bike");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(108, 108, 108))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(backButton)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(imageCodePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rentingTimeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rentingTimeField))
                            .addComponent(returnButton, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rentingTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rentingTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imageCodePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(returnButton))
                .addGap(55, 55, 55))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        MainEntry.move(this, backScreen);
    }//GEN-LAST:event_backButtonActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        try {
            System.out.println("user_____status____scan: " + user.getStatus());
            ScanCodeScreen scs;
            if (user.getStatus() == Constants.USER_RENTING) {
                System.out.println("renting user want to scan");
                scs = new ScanCodeScreen(transaction, bike, user, this);
            } else {
                System.out.println("avail user want to scan");
                scs = new ScanCodeScreen(user, this);
            }

            MainEntry.move(this, scs);
        } catch (SQLException ex) {
            Logger.getLogger(RentingScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_returnButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton backButton;
    private com.hust.group11.ecobikerentalgroup11.boundary.ImageCodePanel imageCodePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable rentingBikeTable;
    private javax.swing.JTextField rentingTimeField;
    private javax.swing.JLabel rentingTimeLabel;
    private javax.swing.JButton returnButton;
    // End of variables declaration//GEN-END:variables
}
